# The command to remove a file.
RM = cmake -E remove_directory

#cmake definition config
cmake_definition+= -DTOOLCHAIN_PREFIX=
cmake_definition+= -DCONFIG_COMPONENT1=y
cmake_definition+= -DCONFIG_COMPONENT2=y
cmake_definition+= -DCONFIG_COMPONENT3=y

include ${SDK_BASE}/project.build
